config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :new, :edit, :show, :update] do
    member do
      get :likes
    end
  end
  
  resources :articles, only: [:index, :destroy, :show, :edit, :update] do
    member do
      get :band
      get :member
    end
    collection do
      get :band
      get :member
      get :band_new
      post :band_create
      get :member_new
      post :member_create
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show ]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  validates :kind, presence: :true
  validates :heading, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true, length: { maximum: 400 }
  validates :gender, presence: true
  
  mount_uploader :image, ImageUploader
  
  # お気に入り機能
  has_many :favorites, dependent: :destroy
  
  # 募集パート
  has_many :article_parts, dependent: :destroy
  has_many :parts, through: :article_parts, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :check_number_of_band, only: [:band_create, :band_new]
  before_action :check_number_of_member, only: [:member_create, :member_new]
  
  def index
    @articles = Article.order(id: :desc).page(params[:page]).per(25)
  end
  
  def band
    @articles = Article.where(kind: 'band').order(id: :desc).page(params[:page]).per(25)
  end
  
  def member
    @articles = Article.where(kind: 'member').order(id: :desc).page(params[:page]).per(25)
  end
  
  def band_create
    @article = current_user.articles.build(article_params)
    @article.kind = 'band'
    if @article.save
      flash[:success] = '記事を投稿しました。'
      redirect_to @article
    else
      @user = current_user
      flash.now[:danger] = '記事の投稿に失敗しました。'
      render :band_new
    end
  end
  
  def member_create
    @article = current_user.articles.build(article_params)
    @article.kind = 'member'
    @article.gender = current_user.gender
    @article.age = current_user.age
    @article.area = current_user.area
    @article.introduction = current_user.introduction
    @article.image = current_user.image
    @article.parts = current_user.parts
    if @article.save
      flash[:success] = '記事を投稿しました。'
      redirect_to @article
    else
      @user = current_user
      @parts_of_member = @article.parts
      flash.now[:danger] = '記事の投稿に失敗しました。'
      render :member_new
    end
  end
  
  def band_new
    @article = Article.new
  end
  
  def member_new
    @article = Article.new
    @parts_of_member = current_user.parts.all.map { |h| h[:name] }
  end
  
  def edit
  end
  
  def show
    @article = Article.find_by(id: params[:id])
    @parts_of_band = @article.parts.all.order(:id).map { |h| h[:name] }
    @parts_of_member = @article.user.parts.all.order(:id).map { |h| h[:name] }
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = '記事は正常に更新されました'
      redirect_to @article
    else
      flash[:danger] = '記事は更新されませんでした'
      render :show
    end
  end

  def destroy
    @article.destroy
    flash[:success] = '記事を削除しました。'
    redirect_to current_user
  end
  
  private

  def article_params
    params.require(:article).permit(:heading, :introduction, :gender, :minimum_age, :maximum_age, :age, :area, :image, part_ids: [])
  end
  
  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    unless @article
      flash[:danger] = '権限がありません。'
      redirect_back(fallback_location: root_path)
    end
  end
  
  def check_number_of_band
    if current_user.articles.where(kind: 'band').count >= 1
      flash[:danger] = 'バンドメンバー募集記事は1つまでしか投稿できません'
      redirect_back(fallback_location: root_path)
    end
  end
  
  def check_number_of_member
    if current_user.articles.where(kind: 'member').count >= 1
      flash[:danger] = 'メンバー加入希望記事は1つまでしか投稿できません'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/views/articles/_articles.html.erb
<% if articles.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>イメージ画像</th>
        <th>記事分類</th>
        <th>見出し</th>
        <th>投稿者</th>
        <th>投稿日時</th>
        <% if logged_in? %>
          <th>ボタン</th>
        <% end %>
      </tr>
    </thead>
    
    <tbody>
      <%= render partial: 'articles/table_row', collection: articles, as: 'article' %>
     </tbody>
  </table>
  
  <% unless current_page?(root_path) %>
    <%= paginate articles %>
  <% end %>
<% end %>

app/views/articles/_table_row.html.erb
<tr class="info">
  <td class="align-middle">
    <% if article.image? %>
      <%= image_tag article.image.url, class: "rounded img-fluid w-10", width: '70px' %>
    <% else %>
      未設定
    <% end %>
  </td>
  <td class="align-middle">
    <% case article.kind %>
    <% when 'band' %>
      <%= link_to 'メンバー募集', band_articles_path, class: "btn btn-dark btn-sm rounded-pill" %>
    <% when 'member' %>
      <%= link_to '加入希望', member_articles_path, class: "btn btn-secondary btn-sm rounded-pill" %>
    <% end %>
  </td>
  <td class="align-middle"><%= link_to article.heading, article %></td>
  <td class="align-middle"><%= link_to article.user.name, article.user %></td>
  <td class="align-middle text-muted"><%= article.created_at %></td>
  <% if logged_in? && article.user.id == current_user.id %>
    <td class="align-middle">
      <%= link_to '編集', edit_article_path(article), class: 'btn btn-success btn-sm rounded-pill'%>
      <%= link_to '削除', article, method: :delete, data: { confirm: '削除してよろしいですか?' }, class: 'btn btn-danger btn-sm rounded-pill ml-2' %>
    </td>
  <% elsif logged_in? %>
    <td class="align-middle"><%= render 'favorites/like_button', article: article %></td>
  <% end %>
</tr>

app/views/articles/_tabs.html.erb
<ul class="nav nav-tabs nav-justified my-5">
  <li class="nav-item lead"><a href="<%= articles_path %>" class="nav-link <%= 'active font-weight-bold' if current_page?(articles_path) %>">記事一覧</a></li>
  <li class="nav-item lead"><a href="<%= band_articles_path %>" class="nav-link <%= 'active font-weight-bold' if current_page?(band_articles_path) %>">バンドメンバー募集記事一覧</a></li>
  <li class="nav-item lead"><a href="<%= member_articles_path %>" class="nav-link <%= 'active font-weight-bold' if current_page?(member_articles_path) %>">メンバー加入希望記事一覧</a></li>
</ul>

app/views/articles/band.html.erb
<%= render 'tabs' %>

<div>
  <%= render 'articles', articles: @articles %>
</div>

app/views/articles/band_new.html.erb
<div class="text-center my-4">
  <h1>バンドメンバー募集記事の作成</h1>
</div>
  
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @article, url: band_create_articles_path, local: true) do |f| %>
    
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :image, 'イメージ画像' %><span class="text-warning pl-2">(任意)</span>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :heading, '記事の見出し(50文字以内)' %><span class="text-danger pl-2">※必須</span>
        <%= f.text_field :heading, class: 'form-control' %>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :gender, '性別' %><br/>
        <%= f.radio_button :gender, '指定なし', checked: true %>
        <%= f.label :gender, '指定なし', value: '指定なし' %>
        <%= f.radio_button :gender, '男性' %>
        <%= f.label :gender, '男性', value: '男性' %>
        <%= f.radio_button :gender, '女性' %>
        <%= f.label :gender, '女性', value: '女性'%>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :minimum_age, '募集年齢' %>
        <%= f.select :minimum_age, ['下限なし', '10代', '20代', '30代', '40代', '50代', '60代'], class: 'form-control' %>
        ~
        <%= f.select :maximum_age, ['20代', '30代', '40代', '50代', '60代', '上限なし'], class: 'form-control' %>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :area, '活動エリア' %>
        <%= f.select :area, %w(指定なし 北海道 青森 岩手 宮城 秋田 山形 福島 茨城 栃木 群馬 埼玉 千葉 東京 神奈川 新潟 富山 石川 福井 山梨 長野 岐阜 静岡 愛知 三重 滋賀 京都 大阪 兵庫 奈良 和歌山 鳥取 島根 岡山 広島 山口 徳島 香川 愛媛 高知 福岡 佐賀 長崎 熊本 大分 宮崎 鹿児島 沖縄), selected: '指定なし', class: 'form-control' %>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :parts_ids, '募集パート' %><span class="text-warning pl-2">(任意)</span><br/>
        <%= f.collection_check_boxes(:part_ids, Part.all, :id, :name) do |part| %>
        <%= part.label{ part.check_box + part.text } %>
        <% end %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduction, '記事内容(400文字以内)' %><span class="text-danger pl-2">※必須</span>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>
      
      <%= f.submit '記事を投稿', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container mt-4">
  
  <div class="text-center">
    <h2>記事の編集</h1>
  </div>
  
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      
      <%= form_with(model: @article, local: true) do |f| %>
        <% case @article.kind %>
        <% when 'band' %>
  
          <%= render 'layouts/error_messages', model: f.object %>
          
          <div class="form-group">
            <%= f.label :image, 'イメージ画像' %><span class="text-warning pl-2">(任意)</span>
            <%= f.file_field :image, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :heading, '記事の見出し(50文字以内)' %><span class="text-danger pl-2">※必須</span>
            <%= f.text_field :heading, class: 'form-control' %>
          </div>
          
          <div class="form-group border-bottom">
            <%= f.label :gender, '性別' %><br/>
            <%= f.radio_button :gender, '指定なし', checked: true %>
            <%= f.label :gender, '指定なし', value: '指定なし' %>
            <%= f.radio_button :gender, '男性' %>
            <%= f.label :gender, '男性', value: '男性' %>
            <%= f.radio_button :gender, '女性' %>
            <%= f.label :gender, '女性', value: '女性'%>
          </div>
          
          <div class="form-group border-bottom">
            <%= f.label :minimum_age, '募集年齢' %>
            <%= f.select :minimum_age, ['下限なし', '10代', '20代', '30代', '40代', '50代', '60代'], class: 'form-control' %>
            ~
            <%= f.select :maximum_age, ['20代', '30代', '40代', '50代', '60代', '上限なし'], class: 'form-control' %>
          </div>
          
          <div class="form-group border-bottom">
            <%= f.label :area, '活動エリア' %>
            <%= f.select :area,
              %w(指定なし 北海道 青森 岩手 宮城 秋田 山形 福島 茨城 栃木 群馬 埼玉 千葉 東京 神奈川 新潟 富山 石川 福井 山梨 長野 岐阜 静岡 愛知 三重 滋賀 京都 大阪 兵庫 奈良 和歌山 鳥取 島根 岡山 広島 山口 徳島 香川 愛媛 高知 福岡 佐賀 長崎 熊本 大分 宮崎 鹿児島 沖縄), selected: '指定なし', class: 'form-control' %>
          </div>
          
          <div class="form-group border-bottom">
            <%= f.label :parts_ids, '募集パート' %><span class="text-warning pl-2">(任意)</span><br/>
            <%= f.collection_check_boxes(:part_ids, Part.all, :id, :name) do |part| %>
            <%= part.label{ part.check_box + part.text } %>
            <% end %>
          </div>
          
          <div class="form-group">
            <%= f.label :introduction, '記事内容(400文字以内)' %><span class="text-danger pl-2">※必須</span>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>
    
        <% when 'member' %>
        
          <%= render 'layouts/error_messages', model: f.object %> 
        
          <div class='text-center py-4'>
            <div>
              <% if @article.image? %>
              <%= image_tag @article.image.url, class: "rounded img-fluid mx-auto", width: '200px' %>
              <% end %>
            </div>
          </div>
        
          <div class="form-group">
            <%= f.label :heading, '記事の見出し(50文字以内)' %><span class="text-danger pl-2">※必須</span>
            <%= f.text_field :heading, autofocus: true, class: 'form-control' %>
          </div>
            
          <dl class="px-5">
            <dt class="text-left font-weight-normal">性別</dt>
            <dd class="pl-3 border"><%= @article.gender %></dd>
            <dt class="text-left font-weight-normal">年齢</dt>
            <dd class="pl-3 border"><%= @article.age %>歳</dd></dd>
            <dt class="text-left font-weight-normal">活動エリア</dt>
            <dd class="pl-3 border"><%= @article.area%></dd>
            <dt class="text-left font-weight-normal mt-3">担当パート</dt>
            <dd class="pl-3 border">担当パート</dd>
            <dt class="text-left font-weight-normal mt-3">記事内容</dt>
            <dd class="pl-3 border"><%= current_user.introduction %></dd>
          </dl>
          
        <% end %>
        
      <%= f.submit '記事を更新', class: 'btn btn-primary btn-block mt-4' %>
      
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class='container px-4 py-4'>
  <%= render 'articles', articles: @articles %>
</div>

app/views/articles/member.html.erb
<%= render 'tabs' %>

<div>
  <%= render 'articles', articles: @articles %>
</div>

app/views/articles/member_new.html.erb
<div class="container mt-4">
  
  <div class="text-center">
    <h1>メンバー加入希望記事の作成</h1>
  </div>
  
  <div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @article, url: member_create_articles_path, local: true) do |f| %>
    
      <%= render 'layouts/error_messages', model: f.object %> 
        
        <div class='text-center py-4'>
          <div>
            <% if current_user.image? %>
            <%= image_tag current_user.image.url, class: "rounded img-fluid mx-auto", width: '200px' %>
            <% end %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :heading, '記事の見出し(50文字以内)', class: 'lead font-weight-bold' %><span class="text-danger pl-2">※必須</span>
          <%= f.text_field :heading, autofocus: true, class: 'form-control' %>
        </div>
          
        <dl class="px-5">
          <dt class="text-left font-weight-normal">性別</dt>
          <dd class="pl-3 border"><%= current_user.gender %></dd>
          <dt class="text-left font-weight-normal">年齢</dt>
          <dd class="pl-3 border"><%= current_user.age %>歳</dd></dd>
          <dt class="text-left font-weight-normal">活動エリア</dt>
          <dd class="pl-3 border"><%= current_user.area %></dd>
          <dt class="text-left font-weight-normal mt-3">担当パート</dt>
          <dd class="pl-3 border">
            <% unless @parts_of_member.empty? %>
              <%= @parts_of_member.join('、') %>
            <% else %>
              指定なし
            <% end %>
          </dd>
          <dt class="text-left font-weight-normal mt-3">記事内容</dt>
          <dd class="pl-3 border"><%= current_user.introduction %></dd>
        </dl>
        
        <%= f.submit '記事を投稿', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>

  
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    
    <h2 class="text-center">記事の詳細</h2>
  
    <div class='text-center py-4'>
      <div>
        <% if @article.image? %>
          <%= image_tag @article.image.url, class: "rounded img-fluid mx-auto", width: '200px' %>
        <% end %>
      </div>
      <% unless current_user == @article.user %>
        <div class="mt-3">
          <% if logged_in? %>
            <%= render 'favorites/like_button', article: @article %>
          <% end %>
        </div>
      <% end %>
    </div>
  
    <p class="border-bottom text-center"><%= @article.heading %></p>
    
    <dl class="px-5">
      <% case @article.kind %>
      <% when 'band' %>
        <dt class="text-left font-weight-normal">募集性別</dt>
        <dd class="pl-3 border"><%= @article.gender %></dd>
        <dt class="text-left font-weight-normal">募集年齢</dt>
        <dd class="pl-3 border"><%= @article.minimum_age %>〜<%= @article.maximum_age %></dd>
        <dt class="text-left font-weight-normal">活動エリア</dt>
        <dd class="pl-3 border"><%= @article.area %></dd>
        <dt class="text-left font-weight-normal mt-3">募集パート</dt>
        <dd class="pl-3 border">
          <% unless @parts_of_band.empty? %>
            <%= @parts_of_band.join('、') %>
          <% else %>
            指定なし
          <% end %>
        </dd>
      <% when 'member' %>
        <dt class="text-left font-weight-normal">性別</dt>
        <dd class="pl-3 border"><%= @article.gender %></dd>
        <dt class="text-left font-weight-normal">年齢</dt>
        <dd class="pl-3 border"><%= @article.age %>歳</dd>
        <dt class="text-left font-weight-normal">活動エリア</dt>
        <dd class="pl-3 border"><%= @article.area %></dd>
        <dt class="text-left font-weight-normal mt-3">担当パート</dt>
        <dd class="pl-3 border">
          <% unless @parts_of_member.empty? %>
            <%= @parts_of_member.join('、') %>
          <% else %>
            指定なし
          <% end %>
        </dd>
      <% end %>
      
      <dt class="text-left font-weight-normal mt-3">記事内容</dt>
      <dd class="text-left pl-3 border"><%= simple_format(@article.introduction) %></dd>
      
    </dl>
    
    <% if logged_in? && @article.user.id == current_user.id %>
      <div class="text-center mt-4">
        <%= link_to '記事を編集', edit_article_path(@article), class: 'btn btn-success rounded-pill' %>
        <%= link_to '記事を削除', @article, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger rounded-pill ml-4' %>
      </div>
      <div class="text-center mt-4">
        <%= link_to 'ユーザプロフィールへ', current_user, class: 'btn btn-outline-info' %>
      </div>
    <% else %>
      <div>投稿者</div>
      <table class="table">
        <tbody>
          <%= render 'users/table_row', user: @article.user %>
        </tbody>
      </table>
    <% end %>
 
    </div>
    
  </div>
</div>