config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :new, :edit, :show, :update] do
    member do
      get :likes
    end
  end
  
  resources :articles, only: [:index, :destroy, :show, :edit, :update] do
    member do
      get :band
      get :member
    end
    collection do
      get :band
      get :member
      get :band_new
      post :band_create
      get :member_new
      post :member_create
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show ]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :gender, presence: true
  validates :birthday, presence: true
  validates :introduction, presence: true, length: { maximum: 400 }
  
  has_secure_password
  
  mount_uploader :image, ImageUploader
  
  # お気に入り機能
  has_many :articles, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :article, dependent: :destroy
  
  # 担当パート
  has_many :user_parts, dependent: :destroy
  has_many :parts, through: :user_parts, dependent: :destroy
  
  # メッセージ機能
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  def age
    d1 = self.birthday.strftime("%Y%m%d").to_i
    d2 = Date.today.strftime("%Y%m%d").to_i
    return (d2 - d1) / 10000
  end
  
  def like(article)
    unless self.articles.include?(article)
     self.favorites.find_or_create_by(article_id: article.id)
    end
  end
  
  def remove_like(article)
    favorite = self.favorites.find_by(article_id: article.id)
    favorite.destroy if favorite
  end
  
  def like?(article)
    self.likes.include?(article)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy, :likes]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def new
    @user = User.new
  end
  
  def edit
    @user = User.find_by(id: params[:id])
    if @user.sample == true
      flash[:danger] = '編集できません。'
      redirect_back(fallback_location: root_path)
    end
  end

  
  def show
    @user = User.find_by(id: params[:id])
    @band_article = @user.articles.find_by(kind: 'band')
    @member_article = @user.articles.find_by(kind: 'member')
    @parts = @user.parts.all.order(:id).map { |h| h[:name] }
    
    if logged_in?
      current_user_entries = Entry.where(user_id: current_user.id)
      user_entries = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        current_user_entries.each do |cu|
          user_entries.each do |u|
            if cu.room_id == u.room_id
              @room =  Room.find_by(id: cu.room_id)
            end
          end
        end
      end
    end
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params) && @user.sample == false
      flash[:success] = 'プロフィールは正常に更新されました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザは更新されませんでした'
      render :edit
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :birthday, :area, :image, :introduction, part_ids: [])
  end
  
  def correct_user
    @user = User.find_by(id: params[:id])
    unless current_user == @user
      flash[:danger] = '権限がありません'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: user, local: true) do |f| %>
    
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :image, 'アイコン画像' %><span class="text-warning pl-1">(任意)</span>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :name, 'アカウント名' %><span class="text-danger pl-1">※必須</span>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
　　　
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %><span class="text-danger pl-1">※必須</span>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <% if request.path_info == signup_path || request.path_info == new_user_path || request.path_info == users_path %>
        <div class="form-group">
          <%= f.label :password, 'パスワード' %><span class="text-danger pl-1">※必須</span>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password_confirmation, 'パスワード(確認)' %><span class="text-danger pl-1">※必須</span>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      <% end %>
      
      <div class="form-group border-bottom">
        <%= f.label :gender, '性別' %><span class="text-danger pl-1">※必須</span><br/>
        <%= f.radio_button :gender, '男性', checked: true %>
        <%= f.label :gender, '男性', value: '男性' %>
        <%= f.radio_button :gender, '女性' %>
        <%= f.label :gender, '女性', value: '女性'%>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :birthday, '生年月日' %><span class="text-danger pl-1">※必須</span>
        <%= f.date_select :birthday, start_year: 1940, end_year: Time.current.year, use_month_numbers: true, date_separator: '/', class: 'form-control' %>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :area, '活動エリア' %><span class="text-warning pl-1">(任意)</span>
        <%= f.select :area, %w(指定なし 北海道 青森 岩手 宮城 秋田 山形 福島 茨城 栃木 群馬 埼玉 千葉 東京 神奈川 新潟 富山 石川 福井 山梨 長野 岐阜 静岡 愛知 三重 滋賀 京都 大阪 兵庫 奈良 和歌山 鳥取 島根 岡山 広島 山口 徳島 香川 愛媛 高知 福岡 佐賀 長崎 熊本 大分 宮崎 鹿児島 沖縄), :selected => '指定なし', class: 'form-control' %>
      </div>
      
      <div class="form-group border-bottom">
        <%= f.label :parts_ids, '担当パート' %><span class="text-warning pl-1">(任意)</span><br/>
        <%= f.collection_check_boxes(:part_ids, Part.all, :id, :name) do |part| %>
        <%= part.label{ part.check_box + part.text }%>
        <% end %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduction, '自己紹介文(400文字以内)' %><span class="text-danger pl-1">※必須</span>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>
      
      <% if request.path_info == signup_path || request.path_info == new_user_path || request.path_info == users_path %>
        <%= f.submit '新規登録', class: 'btn btn-primary btn-block mt-4'%>
        <p class="mt-3">すでに会員登録済みの方はこちら <%= link_to 'ログイン', login_path %></p>
      <% else %>
        <%= f.submit 'プロフィールを更新', class: 'btn btn-primary btn-block mt-4' %>
      <% end %>
      
    <% end %>
    
  </div>
</div>

app/views/users/_table_row.html.erb
<tr>
  <td>
    <% if user.image? %>
      <%= image_tag user.image.url, class: "rounded img-fluid w-10", width: '70px' %>
    <% else %>
      未設定
    <% end %>
  </td>
  <td class="align-middle"><%= link_to user.name, user %></td>
  <td class="align-middle"><%= user.age %>歳</td>
  <td class="align-middle">
    <% if user.area? %>
      <%= user.area %>
    <% else %>
      未設定
    <% end %>
    </td>
  <td class="align-middle">
    <% if user.parts.present? %>
      <%= user.parts.all.order(:id).map { |h| h[:name] }.join('、') %>
    <% else %>
      未設定
    <% end %>
  </td>
</tr>

app/views/users/_users.html.erb
<% if users.any? %>
  <table class="table table-striped">
    
    <thead>
      <tr>
        <th data-field="image" data-sortable="true">ユーザアイコン</th>
        <th data-field="classification" data-sortable="true">ユーザ名</th>
        <th data-field="heading" data-sortable="true">年齢</th>
        <th data-field="name" data-sortable="true">活動エリア</th>
        <th data-field="created_at" data-sortable="true">担当パート</th>
      </tr>
    </thead>
  
    <tbody>
      <%= render partial: 'users/table_row', collection: users, as: 'user' %>
    </tbody>
    
  </table>
  
  <%= paginate users %>

<% end %>

app/views/users/edit.html.erb
<h2 class="text-center my-4">プロフィールの編集</h2>

<%= render 'form', user: @user %>　

app/views/users/index.html.erb
<h2 class="text-center my-4">ユーザ一覧</h2>

<%= render 'users', users: @users %>　

app/views/users/likes.html.erb
<h2 class="text-center my-4">気になるリスト</h2>

<%= render 'articles/articles', articles: @likes %>

app/views/users/new.html.erb
<h2 class="text-center my-4">ユーザ新規登録</h2>

<%= render 'form', user: @user %>　

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
  
    <h2 class="text-center">プロフィール</h2> 

    <div class='text-center py-4'>
      <div>
        <% if @user.image? %>
          <%= image_tag @user.image.url, class: "rounded img-fluid mx-auto", width: '200px' %>
        <% end %>
      </div>
  
      <h3 class="mt-3"><%= @user.name %></h3>
      
      <% if logged_in? %>
        <% if @user.id == current_user.id && @user.sample == false %>  
          <div class="text-center">
            <%= link_to "編集", edit_user_path(@user), class: 'btn btn-sm btn-success rounded-pill ml-2' %> 
          </div>
        <% elsif @user.id != current_user.id %> 
          <% if @room %>
            <div class="text-center">
              <%= link_to 'メッセージを送る', @room, class: 'btn btn-success rounded-pill mt-2' %>
            </div>
          <% else %>
            <%= form_with(model: Room.new, local: true) do |f| %>
              <%= fields_for current_user.entries.build do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit 'メッセージを新規作成', class: 'btn btn-success rounded-pill mt-2' %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      
      
      <div class="lead mt-3">
        <span class="mr-2"><%= @user.gender %></span>
        <span><%= @user.age %>歳</span>
      </div>
    </div>
  
    <dl class="px-5">
      <dt class="text-left font-weight-normal">活動エリア</dt>
      <dd class="pl-3 border"><%= @user.area %><%= '未設定です' if @user.area == nil %></dd>
      <dt class="text-left font-weight-normal mt-3">担当パート</dt>
      <dd class="pl-3 border">
        <% unless @parts.empty? %>
          <%= @parts.join('、') %>
        <% else %>
          指定なし
        <% end %>
      </dd>
      <dt class="text-left font-weight-normal mt-3">自己紹介文</dt>
      <dd class="text-left pl-3 border"><%= simple_format(@user.introduction) %><%= '未記入です' if @user.introduction == nil %></dd>
    </dl>
    
  </div>
</div>

<div class="mt-4">
  <% if @band_article %> 
    <div>バンドメンバー募集記事</div>
    <table class="table">
      <tbody>
        <%= render 'articles/table_row', article: @band_article %> 
      </tbody>
    </table>
    
  <% elsif logged_in? && @user.id == current_user.id %>
    <div class="text-center mt-4">
      <%= link_to 'バンドメンバー募集記事を新規作成する', band_new_articles_path, class: 'btn btn-outline-dark' %>
    </div>
    
  <% else %>
    <div>バンドメンバー募集記事</div>
    <table class="table">
      <tbody>
        <tr class="text-center"><td class="align-center">記事はありません</td></tr>
      </tbody>
    </table>
  <% end %>
</div> 

<div class="mt-4">
  <% if @member_article %>
    <div class="panel panel-default">
      <div class="panel-heading">メンバー加入希望記事</div>
      <table class="table">
        <tbody>
          <%= render 'articles/table_row', article: @member_article %>
        </tbody>
      </table>
    </div>
  <% elsif logged_in? && @user.id ==  current_user.id %>
    <div class="text-center mt-4">
      <%= link_to 'メンバー加入希望記事を新規作成する', member_new_articles_path, class: 'btn btn-outline-secondary' %>
    </div>
  <% else %>
    <div>バンドメンバー募集記事</div>
    <table class="table">
      <tbody>
        <tr class="text-center"><td class="align-center">記事はありません</td></tr>
      </tbody>
    </table>
  <% end %>
</div>