config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :new, :edit, :show, :update] do
    member do
      get :likes
    end
  end
  
  resources :articles, only: [:index, :destroy, :show, :edit, :update] do
    member do
      get :band
      get :member
    end
    collection do
      get :band
      get :member
      get :band_new
      post :band_create
      get :member_new
      post :member_create
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show ]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @current_user_entries = current_user.entries
    my_room_ids = []
    
    @current_user_entries.each do |e|
      my_room_ids << e.room.id
    end
    
    @another_user_entries = Entry.where(room_id: my_room_ids).where('user_id != ?', current_user.id)
  end


  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params.merge(room_id: @room.id))
    redirect_to @room
  end

  def show
    @room = current_user.rooms.find_by(id: params[:id])
    if @room
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      flash[:danger] = '権限がありません。'
      redirect_back(fallback_location: root_path)
    end
    
  end
  
  private
  
  def entry_params
    params.require(:entry).permit(:user_id, :room_id)
  end
end

app/views/rooms/index.html.erb
<h2 class="text-center my-4">メッセージ一覧</h2>

<table class="table">
  
  <thead>
    <tr>
      <th>相手ユーザアイコン</th>
      <th>相手ユーザ名</th>
      <th>最後のメッセージ内容</th>
      <th>送信者</th>
      <th>日時</th>
    </tr>
  </thead>
  
  <tbody>
    <% @another_user_entries.each do |e| %>
      <tr>
        <td>
          <% if e.user.image? %>
            <%= image_tag e.user.image.url, class: "rounded img-fluid mx-auto", width: '50px' %>
          <% else %>
            未設定
          <% end %>
        </td>
        <td><%= link_to e.user.name, e.user %></td>
        <td>
          <% unless e.room.message_ids.empty? %>
            <%= link_to Message.find_by(id: e.room.message_ids.last).content, room_path(e.room.id), class: 'text-dark' %>
          <% else %>
            <%= link_to "メッセージはまだありません", room_path(e.room.id), class: 'text-dark' %>
          <% end %>
        </td>
        <td>
          <% unless e.room.message_ids.empty? %>
            <%= Message.find_by(id: e.room.message_ids.last).user.name %>
          <% end %>
        </td>
        <td class="text-muted">
          <% unless e.room.message_ids.empty? %>
            <%= Message.find_by(id: e.room.message_ids.last).created_at %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/rooms/show.html.erb
<% @entries.each do |e| %>
  <% unless e.user.id == current_user.id %>
    <h2 class="text-center my-4"><%= link_to e.user.name, e.user %>さんとのメッセージ</h2>
  <% end %>
<% end %>

<div class="row">
  <div class="col-sm-8 offset-sm-2">
    
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <% if m.user.id == current_user.id %>
          <div class="media mb-4">
            <div class="media-body">
              <p class="bg-light mt-4 mr-2 ml-5 p-3 border rounded-left rounded-bottom"><%= m.content %></p>
            </div>
            <% if m.user.image? %>
              <%= image_tag m.user.image.url, class: "rounded img-fluid mx-auto", width: '100px' %>
            <% else %>
              未設定
            <% end %>
          </div>
        <% else %>
          <div class="media mb-4">
            <% if m.user.image? %>
              <%= image_tag m.user.image.url, class: "rounded img-fluid mx-auto", width: '100px' %>
            <% else %>
              未設定
            <% end %>
            <div class="media-body">
              <h6 class="ml-2"><%= m.user.name %></h5>
              <p class="bg-light ml-2 p-3 border rounded-right rounded-bottom"><%= m.content %></p>
            </div>
          </div>
        <% end %>
    <% end %>
    <% else %>
      <h5 class="text-center">メッセージはまだありません</h5>
    <% end %>
    
    <div class="border-top pt-4">
      <%= form_for @message do |f| %>
      <%= f.text_field :content, placeholder: 'メッセージを入力して下さい', autofocus: true, size: 90 %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <div class="text-center mt-3">
        <%= f.submit 'メッセージを送る', class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    
    <div class="text-center mt-4">
      <%= link_to "メッセージ一覧に戻る", rooms_path %>
    </div>
  </div>
</div>