config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :new, :edit, :show, :update] do
    member do
      get :likes
    end
  end
  
  resources :articles, only: [:index, :destroy, :show, :edit, :update] do
    member do
      get :band
      get :member
    end
    collection do
      get :band
      get :member
      get :band_new
      post :band_create
      get :member_new
      post :member_create
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show ]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-secondary mt-auto">
  <div class="d-flex justify-content-center">
    <div class="border-right my-3 px-2">
      <%= link_to 'トップページ', root_path, class: 'text-light' %>
    </div>
    <% if logged_in? %>
      <div class="my-3 px-2">
        <%= link_to 'ログアウト', logout_path, method: :delete, class: 'text-light' %>
      </div>
    <% else %>
      <div class="border-right my-3 px-2">
        <%= link_to 'ログイン', login_path, class: 'text-light' %>
      </div>
      <div class="my-3 px-2">
        <%= link_to '新規登録', signup_path, class: 'text-light' %>
      </div>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-dark mb-4">
  <nav class="navbar navbar-expand-sm navbar-info">
    <a class="navbar-brand text-light" href="/">BANDLINE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to '記事一覧', articles_path, class: 'nav-link text-white' %></li>
        <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: 'nav-link text-white' %></li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to '気になるリスト', likes_user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'メッセージ一覧', rooms_path %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link text-white' %></li>
          <li class="nav-item"><%= link_to '新規登録(無料)', signup_path, class: 'nav-link text-white' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bandline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    <style>
      .jumbotron {
        background: url(<%= asset_path 'concert-3387324_1280.jpg' %>) center 45%; 
      }
    </style>
    
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100" >
      
      <%= render 'layouts/header' %>
      
      <div class="container mb-4">
        <%= render 'layouts/flash_messages' %>
  
        <%= yield %>
      </div>
      
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>